### ISSUE TITLE
Running in Automatic1111?

### ISSUE THREAD

**Issue by zono50** [openai/consistencydecoder#13]
Can we use this in automatic1111? or does an extension need to be created first?

**Comment by mathieu-heyarctic** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/tree/consistency-dec

**Comment by shitianfang** [comment]
Is there any way to use the plugin, I don't want to reinstall or upgrade the sd.

**Comment by zono50** [comment]
So just git checkout consistency-dec, then git pull? It said it was already up to date. Also getting the following error when starting automatic11111

Traceback (most recent call last):
  File "/mnt/Kodi_Backup/Applications/stable-diffusion-webui/launch.py", line 48, in <module>
    main()
  File "/mnt/Kodi_Backup/Applications/stable-diffusion-webui/launch.py", line 44, in main
    start()
  File "/mnt/Kodi_Backup/Applications/stable-diffusion-webui/modules/launch_utils.py", line 432, in start
    import webui
  File "/mnt/Kodi_Backup/Applications/stable-diffusion-webui/webui.py", line 13, in <module>
    initialize.imports()
  File "/mnt/Kodi_Backup/Applications/stable-diffusion-webui/modules/initialize.py", line 37, in imports
    from modules import processing, gradio_extensons, ui  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Kodi_Backup/Applications/stable-diffusion-webui/modules/processing.py", line 18, in <module>
    import modules.sd_hijack
  File "/mnt/Kodi_Backup/Applications/stable-diffusion-webui/modules/sd_hijack.py", line 5, in <module>
    from modules import devices, sd_hijack_optimizations, shared, script_callbacks, errors, sd_unet, patches
  File "/mnt/Kodi_Backup/Applications/stable-diffusion-webui/modules/sd_hijack_optimizations.py", line 13, in <module>
    from modules.hypernetworks import hypernetwork
  File "/mnt/Kodi_Backup/Applications/stable-diffusion-webui/modules/hypernetworks/hypernetwork.py", line 13, in <module>
    from modules import devices, sd_models, shared, sd_samplers, hashes, sd_hijack_checkpoint, errors
  File "/mnt/Kodi_Backup/Applications/stable-diffusion-webui/modules/sd_samplers.py", line 1, in <module>
    from modules import sd_samplers_kdiffusion, sd_samplers_timesteps, shared
  File "/mnt/Kodi_Backup/Applications/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 4, in <module>
    from modules import sd_samplers_common, sd_samplers_extra, sd_samplers_cfg_denoiser
  File "/mnt/Kodi_Backup/Applications/stable-diffusion-webui/modules/sd_samplers_common.py", line 6, in <module>
    from modules import devices, images, sd_vae_approx, sd_samplers, sd_vae_taesd, sd_vae_consistency, shared, sd_models
  File "/mnt/Kodi_Backup/Applications/stable-diffusion-webui/modules/sd_vae_consistency.py", line 10, in <module>
    from consistencydecoder import ConsistencyDecoder
ModuleNotFoundError: No module named 'consistencydecoder

insstalled using pip install -r requirements.txt and it completes, but still complains about missing the submodule
